"""
Python SDK for OpenFGA

API version: 1.x
Website: https://openfga.dev
Documentation: https://openfga.dev/docs
Support: https://openfga.dev/community
License: [Apache-2.0](https://github.com/openfga/python-sdk/blob/main/LICENSE)

NOTE: This file was auto generated by OpenAPI Generator (https://openapi-generator.tech). DO NOT EDIT.
"""

import math
import random
import sys


class Math:
    @staticmethod
    def jitter(
        loop_count: int,
        min_wait_in_ms: int,
    ) -> int:
        minimum = int(math.ceil(2**loop_count * min_wait_in_ms))
        maximum = int(math.ceil(2 ** (loop_count + 1) * min_wait_in_ms))

        if "pytest" in sys.modules or minimum == maximum:
            return 0

        return int(random.randrange(minimum, maximum) / 1000)
