"""
Python SDK for OpenFGA

API version: 1.x
Website: https://openfga.dev
Documentation: https://openfga.dev/docs
Support: https://openfga.dev/community
License: [Apache-2.0](https://github.com/openfga/python-sdk/blob/main/LICENSE)

NOTE: This file was auto generated by OpenAPI Generator (https://openapi-generator.tech). DO NOT EDIT.
"""

from typing import Final


# SDK version information
SDK_VERSION: Final[str] = "0.9.7"  # Version of the OpenFGA Python SDK

# User agent for HTTP requests
USER_AGENT: Final[str] = "openfga-sdk python/0.9.7"  # User agent used in HTTP requests

# Sample API domain for examples
SAMPLE_BASE_DOMAIN: Final[str] = (
    "fga.example"  # Example API domain for documentation/tests
)

# Retry configuration
RETRY_MAX_ALLOWED_NUMBER: Final[int] = (
    15  # Maximum allowed number of retries for HTTP requests
)
DEFAULT_MAX_RETRY: Final[int] = 3  # Default maximum number of retries for HTTP requests
DEFAULT_MIN_WAIT_IN_MS: Final[int] = (
    100  # Default minimum wait time between retries in milliseconds
)
MAX_BACKOFF_TIME_IN_SEC: Final[int] = 120  # Maximum backoff time in seconds
RETRY_HEADER_MAX_ALLOWABLE_DURATION_IN_SEC: Final[int] = (
    1800  # Maximum allowable duration for retry headers in seconds
)

# Client configuration
CLIENT_MAX_METHOD_PARALLEL_REQUESTS: Final[int] = (
    10  # Maximum number of parallel requests for a single method
)
CLIENT_MAX_BATCH_SIZE: Final[int] = 50  # Maximum batch size for batch requests
DEFAULT_CONNECTION_TIMEOUT_IN_MS: Final[int] = (
    10000  # Default connection timeout in milliseconds
)

# Token management
TOKEN_EXPIRY_THRESHOLD_BUFFER_IN_SEC: Final[int] = (
    300  # Buffer time in seconds before token expiry to consider it expired
)
TOKEN_EXPIRY_JITTER_IN_SEC: Final[int] = (
    300  # Jitter time in seconds to add randomness to token expiry checks
)

# HTTP headers
CLIENT_METHOD_HEADER: Final[str] = (
    "X-OpenFGA-Client-Method"  # Header used to identify the client method
)
CLIENT_BULK_REQUEST_ID_HEADER: Final[str] = (
    "X-OpenFGA-Client-Bulk-Request-Id"  # Header used to identify bulk requests
)
RETRY_AFTER_HEADER_NAME: Final[str] = (
    "Retry-After"  # Standard HTTP header for retry after
)
RATE_LIMIT_RESET_HEADER_NAME: Final[str] = (
    "X-RateLimit-Reset"  # Rate limit reset header name
)
RATE_LIMIT_RESET_ALT_HEADER_NAME: Final[str] = (
    "X-Rate-Limit-Reset"  # Alternative rate limit reset header name
)
