"""
   Python SDK for OpenFGA

   API version: 0.1
   Website: https://openfga.dev
   Documentation: https://openfga.dev/docs
   Support: https://discord.gg/8naAwJfWN6
   License: [Apache-2.0](https://github.com/openfga/python-sdk/blob/main/LICENSE)

   NOTE: This file was auto generated by OpenAPI Generator (https://openapi-generator.tech). DO NOT EDIT.
"""


import json
from openfga_sdk.exceptions import ApiException
from openfga_sdk.model_utils import validate_and_convert_types
from openfga_sdk.model.internal_error_message_response import InternalErrorMessageResponse
from openfga_sdk.model.path_unknown_error_message_response import PathUnknownErrorMessageResponse
from openfga_sdk.model.validation_error_message_response import ValidationErrorMessageResponse


class AuthenticationError(ApiException):

    def __init__(self, status=None, reason=None, http_resp=None):
        super(AuthenticationError, self).__init__(status, reason, http_resp)


class NotFoundException(ApiException):

    def __init__(self, status=None, reason=None, http_resp=None, configuration=None):
        super(NotFoundException, self).__init__(status, reason, http_resp)
        self._parsed_exception = validate_and_convert_types(
            json.loads(http_resp.data),
            (PathUnknownErrorMessageResponse,),
            ['PathUnknownErrorMessageResponse'],
            True,
            True,
            configuration=configuration
        )

    @property
    def parsed_exception(self):
        """
        Return the parsed exception
        """
        return self._parsed_exception


class UnauthorizedException(ApiException):

    def __init__(self, status=None, reason=None, http_resp=None):
        super(UnauthorizedException, self).__init__(status, reason, http_resp)


class ForbiddenException(ApiException):

    def __init__(self, status=None, reason=None, http_resp=None):
        super(ForbiddenException, self).__init__(status, reason, http_resp)


class ServiceException(ApiException):

    def __init__(self, status=None, reason=None, http_resp=None, configuration=None):
        super(ServiceException, self).__init__(status, reason, http_resp)
        self._parsed_exception = validate_and_convert_types(
            json.loads(http_resp.data),
            (InternalErrorMessageResponse,),
            ['InternalErrorMessageResponse'],
            True,
            True,
            configuration=configuration
        )

    @property
    def parsed_exception(self):
        """
        Return the parsed exception
        """
        return self._parsed_exception


class ValidationException(ApiException):

    def __init__(self, status=None, reason=None, http_resp=None, configuration=None):
        super(ValidationException, self).__init__(status, reason, http_resp)
        self._parsed_exception = validate_and_convert_types(
            json.loads(http_resp.data),
            (ValidationErrorMessageResponse,),
            ['ValidationErrorMessageResponse'],
            True,
            True,
            configuration=configuration
        )

    @property
    def parsed_exception(self):
        """
        Return the parsed exception
        """
        return self._parsed_exception
