"""
Python SDK for OpenFGA

API version: 1.x
Website: https://openfga.dev
Documentation: https://openfga.dev/docs
Support: https://openfga.dev/community
License: [Apache-2.0](https://github.com/openfga/python-sdk/blob/main/LICENSE)

NOTE: This file was auto generated by OpenAPI Generator (https://openapi-generator.tech). DO NOT EDIT.
"""

from unittest.mock import AsyncMock, patch

import pytest

from openfga_sdk.common.open_fga_api import ApiResponse
from openfga_sdk.common.options import GetStoreRequestOptions
from openfga_sdk.models.get_store_response import GetStoreResponse
from openfga_sdk.protocols import ApiResponseProtocol, OpenFgaClientProtocol


@pytest.fixture
def api_request_response(
    mock_api_response_get_store_deserialized: GetStoreResponse,
) -> ApiResponseProtocol:
    return ApiResponse(
        deserialized=mock_api_response_get_store_deserialized,
    )


@pytest.fixture
def api_request_conditions(
    api_request_response: ApiResponse,
):
    return {
        "attribute": "get_store",
        "new": AsyncMock(return_value=api_request_response),
    }


@pytest.mark.asyncio
class TestOpenFgaClientGetStoreEndpoint:
    """
    @covers openfga_sdk.client.OpenFgaClient.get_store
    """

    async def test_create_get_issues_request(
        self,
        client: OpenFgaClientProtocol,
        mock_api_response_get_store,
        api_request_conditions,
    ):
        """
        Test that the get_store method issues a request to OpenFgaApi.
        """
        with patch.object(client.api, **api_request_conditions) as api_request:
            await client.get_store(mock_api_response_get_store["id"])

            api_request.assert_called_once()

    async def test_get_store_returns_expected_response(
        self,
        client: OpenFgaClientProtocol,
        mock_api_response_get_store_deserialized: GetStoreResponse,
        mock_api_response_get_store,
        api_request_conditions,
    ):
        """
        Test that the get_store method returns a GetStoreResponse instance containing the expected response.
        """
        with patch.object(client.api, **api_request_conditions):
            response = await client.get_store(mock_api_response_get_store["id"])

            assert response == mock_api_response_get_store_deserialized

    async def test_get_store_returns_full_response(
        self,
        client: OpenFgaClientProtocol,
        mock_api_response_get_store,
        api_request_response: ApiResponse,
        api_request_conditions,
    ):
        """
        Test that the get_store method returns an ApiResponse instance containing the expected response.
        """
        options = GetStoreRequestOptions(
            store_id=mock_api_response_get_store["id"],
            return_response=True,
        )

        with patch.object(client.api, **api_request_conditions):
            response = await client.get_store(
                mock_api_response_get_store["id"], options
            )

            assert response == api_request_response
