"""
Python SDK for OpenFGA

API version: 1.x
Website: https://openfga.dev
Documentation: https://openfga.dev/docs
Support: https://openfga.dev/community
License: [Apache-2.0](https://github.com/openfga/python-sdk/blob/main/LICENSE)

NOTE: This file was auto generated by OpenAPI Generator (https://openapi-generator.tech). DO NOT EDIT.
"""

import uuid

from unittest.mock import AsyncMock, patch

import pytest

from openfga_sdk.common.open_fga_api import ApiResponse
from openfga_sdk.common.options import DeleteStoreRequestOptions
from openfga_sdk.protocols import ApiResponseProtocol, OpenFgaClientProtocol


@pytest.fixture
def api_request_response() -> ApiResponseProtocol:
    return ApiResponse(
        deserialized=None,
    )


@pytest.fixture
def api_request_conditions(
    api_request_response: ApiResponse,
):
    return {
        "attribute": "delete_store",
        "new": AsyncMock(return_value=api_request_response),
    }


@pytest.mark.asyncio
class TestOpenFgaClientDeleteStoreEndpoint:
    """
    @covers openfga_sdk.client.OpenFgaClient.delete_store
    """

    async def test_delete_store_issues_request(
        self,
        client: OpenFgaClientProtocol,
        api_request_conditions,
    ):
        """
        Test that the delete_store method issues a request to OpenFgaApi.
        """
        with patch.object(client.api, **api_request_conditions) as api_request:
            await client.delete_store(str(uuid.uuid4()))

            api_request.assert_called_once()

    async def test_delete_store_returns_expected_response(
        self,
        client: OpenFgaClientProtocol,
        api_request_conditions,
    ):
        """
        Test that the delete_store method returns the expected response.
        """
        with patch.object(client.api, **api_request_conditions):
            response = await client.delete_store(str(uuid.uuid4()))

            assert response is None

    async def test_delete_store_returns_full_response(
        self,
        client: OpenFgaClientProtocol,
        api_request_response: ApiResponse,
        api_request_conditions,
    ):
        """
        Test that the delete_store method returns an ApiResponse instance containing the expected response.
        """
        options = DeleteStoreRequestOptions(
            return_response=True,
        )

        with patch.object(client.api, **api_request_conditions):
            response = await client.delete_store(str(uuid.uuid4()), options)

            assert response == api_request_response
